name: Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.
        
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
      
    - run: npm run report:merge
    - run: npm run report:mocha
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        GITHUG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh_pages
        FOLDER: mochawesome-report
